// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: staff/cleaning_request.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Actor that produced the message.
type RequestType int32

const (
	// Default zero value.
	RequestType_UNSPECIFIED RequestType = 0
	// Guest-originated message.
	RequestType_PREPARE_FOR_GUEST RequestType = 1
	// System-originated message.
	RequestType_DAILY_CLEANING    RequestType = 2
	RequestType_FULL_CLEANING     RequestType = 3
	RequestType_PREPARE_FOR_SLEEP RequestType = 4
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PREPARE_FOR_GUEST",
		2: "DAILY_CLEANING",
		3: "FULL_CLEANING",
		4: "PREPARE_FOR_SLEEP",
	}
	RequestType_value = map[string]int32{
		"UNSPECIFIED":       0,
		"PREPARE_FOR_GUEST": 1,
		"DAILY_CLEANING":    2,
		"FULL_CLEANING":     3,
		"PREPARE_FOR_SLEEP": 4,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_staff_cleaning_request_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_staff_cleaning_request_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_staff_cleaning_request_proto_rawDescGZIP(), []int{0}
}

type CleaningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Request       RequestType            `protobuf:"varint,2,opt,name=request,proto3,enum=staff.RequestType" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleaningRequest) Reset() {
	*x = CleaningRequest{}
	mi := &file_staff_cleaning_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleaningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleaningRequest) ProtoMessage() {}

func (x *CleaningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_cleaning_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleaningRequest.ProtoReflect.Descriptor instead.
func (*CleaningRequest) Descriptor() ([]byte, []int) {
	return file_staff_cleaning_request_proto_rawDescGZIP(), []int{0}
}

func (x *CleaningRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CleaningRequest) GetRequest() RequestType {
	if x != nil {
		return x.Request
	}
	return RequestType_UNSPECIFIED
}

var File_staff_cleaning_request_proto protoreflect.FileDescriptor

const file_staff_cleaning_request_proto_rawDesc = "" +
	"\n" +
	"\x1cstaff/cleaning_request.proto\x12\x05staff\"[\n" +
	"\x0fCleaningRequest\x12\x1a\n" +
	"\broomName\x18\x01 \x01(\tR\broomName\x12,\n" +
	"\arequest\x18\x02 \x01(\x0e2\x12.staff.RequestTypeR\arequest*s\n" +
	"\vRequestType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PREPARE_FOR_GUEST\x10\x01\x12\x12\n" +
	"\x0eDAILY_CLEANING\x10\x02\x12\x11\n" +
	"\rFULL_CLEANING\x10\x03\x12\x15\n" +
	"\x11PREPARE_FOR_SLEEP\x10\x04B>Z<github.com/Kenji-Uema/staffSimulator/internal/domain/dto;dtob\x06proto3"

var (
	file_staff_cleaning_request_proto_rawDescOnce sync.Once
	file_staff_cleaning_request_proto_rawDescData []byte
)

func file_staff_cleaning_request_proto_rawDescGZIP() []byte {
	file_staff_cleaning_request_proto_rawDescOnce.Do(func() {
		file_staff_cleaning_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_staff_cleaning_request_proto_rawDesc), len(file_staff_cleaning_request_proto_rawDesc)))
	})
	return file_staff_cleaning_request_proto_rawDescData
}

var file_staff_cleaning_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_staff_cleaning_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_staff_cleaning_request_proto_goTypes = []any{
	(RequestType)(0),        // 0: staff.RequestType
	(*CleaningRequest)(nil), // 1: staff.CleaningRequest
}
var file_staff_cleaning_request_proto_depIdxs = []int32{
	0, // 0: staff.CleaningRequest.request:type_name -> staff.RequestType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_staff_cleaning_request_proto_init() }
func file_staff_cleaning_request_proto_init() {
	if File_staff_cleaning_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_staff_cleaning_request_proto_rawDesc), len(file_staff_cleaning_request_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_staff_cleaning_request_proto_goTypes,
		DependencyIndexes: file_staff_cleaning_request_proto_depIdxs,
		EnumInfos:         file_staff_cleaning_request_proto_enumTypes,
		MessageInfos:      file_staff_cleaning_request_proto_msgTypes,
	}.Build()
	File_staff_cleaning_request_proto = out.File
	file_staff_cleaning_request_proto_goTypes = nil
	file_staff_cleaning_request_proto_depIdxs = nil
}
