// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event/time_event.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeEvent) Reset() {
	*x = TimeEvent{}
	mi := &file_event_time_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeEvent) ProtoMessage() {}

func (x *TimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_time_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeEvent.ProtoReflect.Descriptor instead.
func (*TimeEvent) Descriptor() ([]byte, []int) {
	return file_event_time_event_proto_rawDescGZIP(), []int{0}
}

func (x *TimeEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_event_time_event_proto protoreflect.FileDescriptor

const file_event_time_event_proto_rawDesc = "" +
	"\n" +
	"\x16event/time_event.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\";\n" +
	"\tTimeEvent\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04timeB>Z<github.com/Kenji-Uema/staffSimulator/internal/domain/dto;dtob\x06proto3"

var (
	file_event_time_event_proto_rawDescOnce sync.Once
	file_event_time_event_proto_rawDescData []byte
)

func file_event_time_event_proto_rawDescGZIP() []byte {
	file_event_time_event_proto_rawDescOnce.Do(func() {
		file_event_time_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_time_event_proto_rawDesc), len(file_event_time_event_proto_rawDesc)))
	})
	return file_event_time_event_proto_rawDescData
}

var file_event_time_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_event_time_event_proto_goTypes = []any{
	(*TimeEvent)(nil),             // 0: event.TimeEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_event_time_event_proto_depIdxs = []int32{
	1, // 0: event.TimeEvent.time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_event_time_event_proto_init() }
func file_event_time_event_proto_init() {
	if File_event_time_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_time_event_proto_rawDesc), len(file_event_time_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_time_event_proto_goTypes,
		DependencyIndexes: file_event_time_event_proto_depIdxs,
		MessageInfos:      file_event_time_event_proto_msgTypes,
	}.Build()
	File_event_time_event_proto = out.File
	file_event_time_event_proto_goTypes = nil
	file_event_time_event_proto_depIdxs = nil
}
