// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: clock/nowService.proto

package clock

import (
	context "context"
	dto "github.com/Kenji-Uema/staffSimulator/internal/domain/dto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClockService_Now_FullMethodName = "/clock.ClockService/Now"
)

// ClockServiceClient is the client API for ClockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClockServiceClient interface {
	Now(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*dto.TimeEvent, error)
}

type clockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClockServiceClient(cc grpc.ClientConnInterface) ClockServiceClient {
	return &clockServiceClient{cc}
}

func (c *clockServiceClient) Now(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*dto.TimeEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.TimeEvent)
	err := c.cc.Invoke(ctx, ClockService_Now_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClockServiceServer is the server API for ClockService service.
// All implementations must embed UnimplementedClockServiceServer
// for forward compatibility.
type ClockServiceServer interface {
	Now(context.Context, *emptypb.Empty) (*dto.TimeEvent, error)
	mustEmbedUnimplementedClockServiceServer()
}

// UnimplementedClockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClockServiceServer struct{}

func (UnimplementedClockServiceServer) Now(context.Context, *emptypb.Empty) (*dto.TimeEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method Now not implemented")
}
func (UnimplementedClockServiceServer) mustEmbedUnimplementedClockServiceServer() {}
func (UnimplementedClockServiceServer) testEmbeddedByValue()                      {}

// UnsafeClockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClockServiceServer will
// result in compilation errors.
type UnsafeClockServiceServer interface {
	mustEmbedUnimplementedClockServiceServer()
}

func RegisterClockServiceServer(s grpc.ServiceRegistrar, srv ClockServiceServer) {
	// If the following call panics, it indicates UnimplementedClockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClockService_ServiceDesc, srv)
}

func _ClockService_Now_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClockServiceServer).Now(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClockService_Now_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClockServiceServer).Now(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ClockService_ServiceDesc is the grpc.ServiceDesc for ClockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clock.ClockService",
	HandlerType: (*ClockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Now",
			Handler:    _ClockService_Now_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clock/nowService.proto",
}
