// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clock/nowService.proto

package clock

import (
	dto "github.com/Kenji-Uema/staffSimulator/internal/domain/dto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_clock_nowService_proto protoreflect.FileDescriptor

const file_clock_nowService_proto_rawDesc = "" +
	"\n" +
	"\x16clock/nowService.proto\x12\x05clock\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16event/time_event.proto2?\n" +
	"\fClockService\x12/\n" +
	"\x03Now\x12\x16.google.protobuf.Empty\x1a\x10.event.TimeEventBJZHgithub.com/Kenji-Uema/staffSimulator/internal/transport/grpc/clock;clockb\x06proto3"

var file_clock_nowService_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
	(*dto.TimeEvent)(nil), // 1: event.TimeEvent
}
var file_clock_nowService_proto_depIdxs = []int32{
	0, // 0: clock.ClockService.Now:input_type -> google.protobuf.Empty
	1, // 1: clock.ClockService.Now:output_type -> event.TimeEvent
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clock_nowService_proto_init() }
func file_clock_nowService_proto_init() {
	if File_clock_nowService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clock_nowService_proto_rawDesc), len(file_clock_nowService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clock_nowService_proto_goTypes,
		DependencyIndexes: file_clock_nowService_proto_depIdxs,
	}.Build()
	File_clock_nowService_proto = out.File
	file_clock_nowService_proto_goTypes = nil
	file_clock_nowService_proto_depIdxs = nil
}
